/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bikeshop.gui;

import bikeshop.modelos.PessoaCliente;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;

/**
 *
 * @author victo
 */
public class JFrame_MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form JFrame_MenuPrincipal
     */
    public JFrame_MenuPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        label1 = new java.awt.Label();
        jButton_Cliente = new javax.swing.JButton();
        jLabel_Descricao = new javax.swing.JLabel();
        jButton_Atender = new javax.swing.JButton();
        jButton_Inventário = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        label1.setAlignment(java.awt.Label.CENTER);
        label1.setFont(new java.awt.Font("Freehand521 BT", 0, 70)); // NOI18N
        label1.setText("Bike Shop");

        jButton_Cliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/arte/user.png"))); // NOI18N
        jButton_Cliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton_ClienteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton_ClienteMouseExited(evt);
            }
        });

        jLabel_Descricao.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Descricao.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jButton_Atender.setIcon(new javax.swing.ImageIcon(getClass().getResource("/arte/handshake.png"))); // NOI18N
        jButton_Atender.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton_AtenderMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton_AtenderMouseExited(evt);
            }
        });

        jButton_Inventário.setIcon(new javax.swing.ImageIcon(getClass().getResource("/arte/bicycle2.png"))); // NOI18N
        jButton_Inventário.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton_InventárioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton_InventárioMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel_Descricao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jButton_Atender)
                .addGap(18, 18, 18)
                .addComponent(jButton_Cliente)
                .addGap(18, 18, 18)
                .addComponent(jButton_Inventário)
                .addGap(12, 12, 12))
            .addComponent(label1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 94, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton_Cliente, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton_Inventário, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton_Atender, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(90, 90, 90)
                .addComponent(jLabel_Descricao, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_ClienteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_ClienteMouseEntered
        jLabel_Descricao.setText("Clientes");
    }//GEN-LAST:event_jButton_ClienteMouseEntered

    private void jButton_ClienteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_ClienteMouseExited
        jLabel_Descricao.setText("");
    }//GEN-LAST:event_jButton_ClienteMouseExited

    private void jButton_AtenderMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_AtenderMouseEntered
        jLabel_Descricao.setText("Atendimento");
    }//GEN-LAST:event_jButton_AtenderMouseEntered

    private void jButton_AtenderMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_AtenderMouseExited
        jLabel_Descricao.setText("");
    }//GEN-LAST:event_jButton_AtenderMouseExited

    private void jButton_InventárioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_InventárioMouseEntered
        jLabel_Descricao.setText("Inventário");
    }//GEN-LAST:event_jButton_InventárioMouseEntered

    private void jButton_InventárioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_InventárioMouseExited
        jLabel_Descricao.setText("");
    }//GEN-LAST:event_jButton_InventárioMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrame_MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrame_MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrame_MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrame_MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrame_MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Atender;
    private javax.swing.JButton jButton_Cliente;
    private javax.swing.JButton jButton_Inventário;
    private javax.swing.JLabel jLabel_Descricao;
    private javax.swing.JPanel jPanel2;
    private java.awt.Label label1;
    // End of variables declaration//GEN-END:variables
}
